config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :skills
  end

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  devise_for :users
  
  resources :users do
    member do
      get 'posts', to: 'pics#user_pics'
    end
    member do
      put 'edit', to: 'users#edit'
    end
    collection do
      get :explore
    end
  end
  
  resources :categories do
    resources :jobs
  end
  
  resources :pics do
    member do
      put 'like', to: 'pics#upvote'
    end
    resources :comments
  end
  root "pics#index"
  
  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :category
    
    validates :title, :presence => true
    validates :description, :presence => true
    validates :exp_required, :presence => true
    validates :category_id, :presence => true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_category, only: [:index, :new, :create, :show]
  before_action :set_job, only: [:show]
  
  def index
    @jobs = @category.current_category_jobs.all
  end
  
  def new
    @job = @category.current_category_jobs.build(job_params)
  end

  def create
    @job = @category.current_category_jobs.build(job_params)
    if @job.save
      redirect_to category_jobs_path(@category), notice: "New Job been added successfully!"
    else
      render 'new'
    end
  end

  def show
  end

  def update
  end

  def edit
  end

  def destroy
  end
  
  private
  def job_params
    # params.require(:job).permit(:title, :description, :exp_required, :salary, :location, :company_name, :category_id)
    params.fetch(:job, {}).permit(:title, :description, :exp_required, :salary, :location, :company_name, :category_id, :key_skills)
  end
  
  def set_category
    @category = Category.find(params[:category_id])
  end
  
  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
.col-md-6.col-md-offset-3
  .row
    = simple_form_for [:category, @job]  do |f|
      - if @job.errors.any?
        #errors
          %h2
          = pluralize(@job.errors.count, 'error')
          prevented this Pic from saving
          %ul
            - @job.errors.full_messages.each do |msg|
              %li= msg
    
      .form-group
        = f.input :title, input_html: {class: 'form-control'}
      .form-group
        = f.input :description, input_html: {class: 'form-control'}
      .form-group
        = f.input :exp_required, input_html: {class: 'form-control'}
      .form-group
        = f.input :salary, input_html: {class: 'form-control'}
      .form-group
        = f.input :location, input_html: {class: 'form-control'}
      .form-group
        = f.input :company_name, input_html: {class: 'form-control'}
      .form-group
        = f.input :key_skills, input_html: {class: 'form-control'}  
      = f.button :submit, class: 'btn btn-info'

app/views/jobs/_job.html.haml
.panel.panel-default
  .panel-body
    .col-lg-12.no-padding
      .col-lg-12.no-padding
        %b= link_to job.title, category_job_path(category, job)
      .col-lg-12.no-padding
        .label.label-default= job.company_name
      .col-lg-3.no-padding.fa.fa-suitcase
        %span= job.exp_required
      .col-lg-3.no-padding.fa.fa-location-arrow
        = job.location
  .panel-footer
    .col-lg-3.no-padding.fa.fa-inr
      %span.fa.fa-heart.pull-left
      = job.salary.strip
    .col-lg-3.no-padding.glyphicon.glyphicon-user
      PostedBy
    .col-lg-3.no-padding
      Test
    .col-lg-3.no-padding
      = time_ago_in_words(job.created_at) + ' ago'

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.haml
.col-lg-3.col-lg-offset-1
  .panel.panel-default
    .panel-body
      .col-lg-12
        Find Jobs For
      .col-lg-12
        %hr 
          Testing
      .col-lg-12
        %hr 
          Skills
  .panel.panel-default
    .panel-body
      .col-lg-12
        Refine Results
      .col-lg-12
        %hr 
          Freshness
      .col-lg-12
        %hr 
          .dropdown
            %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              Dropdown
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link
      .col-lg-12
        %hr 
          .dropdown
            %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              Dropdown
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link          

-if @jobs.blank?
  .col-lg-6
    = 'No Jobs found'
    = link_to "Add New Job", new_category_job_path(@category), class: 'btn btn-default'
- else
  .col-lg-6
    - @jobs.each do |job|
      = render partial: 'job', locals: {job: job, category: @category}
.row
  .col-lg-3
    = link_to "Add New Job", new_category_job_path(@category), class: 'btn btn-default'
    = link_to "Back", categories_path, class: 'btn btn-default'

app/views/jobs/new.html.haml
%h1 Add New Job
= render 'form'

app/views/jobs/show.html.haml
.col-lg-8.col-lg-offset-1
  = render partial: 'job', locals: {job: @job, category: @category}
.col-lg-8.col-lg-offset-1
  .panel.panel-default
    .panel-body
      .col-lg-12.no-padding
        %p Job Description
      .col-lg-12.no-padding
        = @job.description

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>