config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :skills
  end

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  devise_for :users
  
  resources :users do
    member do
      get 'posts', to: 'pics#user_pics'
    end
    member do
      put 'edit', to: 'users#edit'
    end
    collection do
      get :explore
    end
  end
  
  resources :categories do
    resources :jobs
  end
  
  resources :pics do
    member do
      put 'like', to: 'pics#upvote'
    end
    resources :comments
  end
  root "pics#index"
  
  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics
  # :dependent => :destroy user delete functionality need to check with this.
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
         
  def follow(user_id)  
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:update]

    def explore
        @users = User.all.order("created_at DESC")
    end

    def update

        if @user.edit(user_params)
            redirect_to root_path
        else
          redirect_to root_path, notice: 'Opps something went wrong!'
        end
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:avatar, :id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_avatar_select(user)
    return image_tag user.avatar.url(:medium), id: 'image-preview', class: 'img-responsive img-circle profile-image' if user&.avatar&.exists?

    image_tag 'upload.png', id: 'image-preview',
              class: 'img-responsive img-circle profile-image'
  end
end

app/views/users/explore.html.haml
.col-md-6.col-md-offset-3
  - @users.each do |user|
    - if user != current_user
      .row
        .panel.panel-default
          .panel-body
            %div.col-md-3
              - if user.avatar.exists?
                = image_tag user.avatar.url(:medium), class: 'img-circular-explore'
              - else
                = image_tag '/assets/upload.png', class: 'img-circular-explore'
            %div.col-md-7
              %span= link_to user.try(:email), posts_user_path(user)
              // %span= link_to 'Follow', root_path, class: 'btn btn-default pull-right'
              - if current_user_is_following(current_user.id, user.id)
                = link_to 'Following', unfollow_user_path(user), remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post
              - else
                = link_to 'Follow', follow_user_path(user), remote: true,class: 'btn follow-button', id: 'follow-button', method: :post
        