config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :skills
  end

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  devise_for :users
  
  resources :users do
    member do
      get 'posts', to: 'pics#user_pics'
    end
    member do
      put 'edit', to: 'users#edit'
    end
    collection do
      get :explore
    end
  end
  
  resources :categories do
    resources :jobs
  end
  
  resources :pics do
    member do
      put 'like', to: 'pics#upvote'
    end
    resources :comments
  end
  root "pics#index"
  
  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/pic.rb
class Pic < ApplicationRecord
  has_many :comments, :through => 'user'
  has_many :comments
  # :dependent => :destroy pic delete functionality need to check with this.
  acts_as_votable
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :update, :destroy, :edit, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pics = Pic.all.order("created_at DESC")
  end

  def show
    @comment = @pic.comments.new
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)
    if @pic.save
      redirect_to @pic, notice: 'Successfully created pic'
    else
      render 'new'
    end
  end
  
  def user_pics
    @user = User.find(params[:id])
    @pics = @user.pics
  end

  def edit

  end

  def update
    if @pic.edit(pic_params)
      redirect_to @pic, notice: 'Contgrats pic was udpated'
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  def upvote
    @pic.upvote_by current_user
    redirect_to :back
  end

  private
  def pic_params
    params.require(:pic).permit(:title, :description, :user_id, :image)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end
end

app/helpers/pics_helper.rb
module PicsHelper
    def current_user_is_following(current_user_id, followed_user_id)
        relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
        return true if relationship
    end
end

app/views/pics/_form.html.haml
= simple_form_for @pic, html:{ multipart: true} do |f|
  - if @pic.errors.any?
    #errors
      %h2
      = pluralize(@pic.errors.count, 'error')
      prevented this Pic from saving
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: {class: 'form-control'}
  .form-group
    = f.input :title, input_html: {class: 'form-control'}
  .form-group
    = f.input :description, input_html: {class: 'form-control'}
  = f.button :submit, class: 'btn btn-info'

app/views/pics/_load_pics.html.haml
.col-md-12
  #pics.transitions-enabled
    - @pics.each do |pic|
      .box.panel.panel-default
        = link_to (image_tag pic.image.url), pic, class: 'thumbnail'
        %h2= link_to pic.title, pic_path(pic)

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Fix Pic!
      .panel-body
        .current_image
          %strong.center Right Now
          = image_tag @pic.image.url(:medium), :class=> "img-circular"
        = render 'form'

app/views/pics/index.html.haml
- if current_user && !current_user.avatar.exists?
  .col-md-6.col-md-offset-3
    .row
      .panel.panel-default
        .panel-body
        = simple_form_for current_user, method: :put, html: { multipart: true } do |f|
          .image-upload
            %label{:for => "user_avatar"}
              .img-circular
                = profile_avatar_select(@user)
              = f.input :avatar, onChange: 'loadFile(event)'
          .form-group.text-center
          = f.submit "Update Profile", class: 'btn btn-success'
= render 'load_pics', locals: { pics: @pics }

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Post Pic
      .panel-body
        = render 'form'

app/views/pics/show.html.haml
#pic_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel.heading.pic_image
        %p= image_tag @pic.image.url
      .panel-body
        %h1= @pic.title
        %p= @pic.description
      .panel-footer
        .row
          .col-md-6
            %p.user
              by
              = @pic.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_pic_path(@pic), method: :put, class: 'btn btn-default' do
                %span.glyphicon.glyphicon-thumbs-up
                = @pic.get_upvotes.size
              %a.btn.btn-default{href: '#'}
                %span.glyphicon.glyphicon-comment
                = @pic.comments.size
              - if user_signed_in?
                = link_to 'Edit', edit_pic_path, class: 'btn btn-info'
                = link_to 'Delete', pic_path, method: :delete, data: {confirm: "Are your sure!"}, class: 'btn btn-danger'
          .col-md-12
            - @pic.comments.each do |com|
              %ul
                %li
                  %span= com.user.try(:email)
                  %span= com.comments
          .col-md-12
            = simple_form_for [@pic, Comment.new], :remote => true do |c|
              .form-group
                = c.input :comments, input_html: {class: 'form-control comments_data', :placeholder => 'Add comments'}
              = c.button :submit, class: 'btn btn-info'

app/views/pics/user_pics.html.haml
.col-md-6.col-md-offset-4
  .row
    -#= @pics.first.user.email
    %span
      - if @user == current_user
        = link_to 'Edit Profile', edit_user_registration_path, class: 'btn edit-button'
      - else
        %div.col-md-3
          %span= @user.email
        %div.col-md-3  
          - if current_user_is_following(current_user.id, @user.id)
            = link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post
          - else
            = link_to 'Follow', follow_user_path, remote: true,class: 'btn follow-button', id: 'follow-button', method: :post
  .row
    %span
      %b= @pics.count 
    Posts
    %span 0 Followers
    %span 0 Following
   
= render 'load_pics', locals: { pics: @pics }