config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resources :skills
  end

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  devise_for :users
  
  resources :users do
    member do
      get 'posts', to: 'pics#user_pics'
    end
    member do
      put 'edit', to: 'users#edit'
    end
    collection do
      get :explore
    end
  end
  
  resources :categories do
    resources :jobs
  end
  
  resources :pics do
    member do
      put 'like', to: 'pics#upvote'
    end
    resources :comments
  end
  root "pics#index"
  
  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

end

app/models/category.rb
class Category < ApplicationRecord
    validates :job_category_name, :presence => true
    has_many :current_category_jobs, class_name: 'Job'
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show]

    def index
        @categories = Category.all.order("created_at DESC")
        @category = Category.new
    end
    
    def new
        @category = Category.new
    end
    
    def show
    end
    
    def create
        @category = Category.create(category_params)
        if @category.save
            @categories = Category.all.order("created_at DESC")
        else
            
        end
    end
    
    private
    def category_params
        params.require(:category).permit(:job_category_name)
    end
    
    def set_category
        @category = Category.find(params[:id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, remote: true do |f|
  - if @category.errors.any?
    #errors
      %h2
      = pluralize(@categorypic.errors.count, 'error')
      prevented this Pic from saving
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.input :job_category_name, input_html: {class: 'form-control'}
  = f.button :submit, class: 'btn btn-info'
  = link_to 'Cancel', categories_path, class: 'btn btn-danger'

app/views/categories/_render_collection.html.haml
.panel.panel-default
  .panel-body
    - @categories.each do |category|
      .col-md-3.box.text-center
        = link_to category.job_category_name, category, class: 'thumbnail'

app/views/categories/create.js.erb
<% if @category.errors.any? %>
  alert("ERROR(S): <%= j @category.errors.full_messages.join('; ') %>")
<% else %>
    $("#categories").html("").append("<%= escape_javascript(render :partial => 'categories/render_collection', locals: {categories: @categories}) %>");
    $("#new_category").html("");
    $("#new_category_link").show();
<% end %>

app/views/categories/index.html.haml
#categories.row
  .panel.panel-default
    .panel-body
      - @categories.each do |category|
        .col-md-3.box.text-center
          = link_to category.job_category_name, category_jobs_path(category), class: 'thumbnail'

%div#new_category
= link_to 'New Category', new_category_path, id: 'new_category_link', :remote => true, class: 'btn btn-primary'

app/views/categories/index.js.erb
$("#categories").append("<%= render :partial => 'categories/render_collection', locals: {categories: @categories} %>");

app/views/categories/new.html.haml
%h1 New Category

= render 'form'

app/views/categories/new.js.erb
$("#new_category_link").hide();
$("#new_category").show();
$("#new_category").append("<%= escape_javascript(render :partial => 'categories/form', locals: {category: @category} ) %>");

app/views/categories/show.html.haml
%h1 Listing All #{@category.job_category_name.camelize} jobs